title: Xiaowei Ren
logo: /assets/img/Xiaowei_Ren.jpg
description: Ph.D. at the University of British Columbia
description: "Address: 147, 6335 Thunderbird Residence, UBC, Vancouver, BC, Canada, V6T 2G9"
theme: jekyll-theme-minimal
